// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Compra.proto
// Protobuf Java Version: 4.29.0

package compra;

public final class CompraOuterClass {
  private CompraOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      CompraOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompraOrBuilder extends
      // @@protoc_insertion_point(interface_extends:compra.Compra)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Name of the client
     * </pre>
     *
     * <code>string nomeCliente = 1;</code>
     * @return The nomeCliente.
     */
    java.lang.String getNomeCliente();
    /**
     * <pre>
     * Name of the client
     * </pre>
     *
     * <code>string nomeCliente = 1;</code>
     * @return The bytes for nomeCliente.
     */
    com.google.protobuf.ByteString
        getNomeClienteBytes();

    /**
     * <pre>
     * List of products (repeated field)
     * </pre>
     *
     * <code>repeated string produtos = 2;</code>
     * @return A list containing the produtos.
     */
    java.util.List<java.lang.String>
        getProdutosList();
    /**
     * <pre>
     * List of products (repeated field)
     * </pre>
     *
     * <code>repeated string produtos = 2;</code>
     * @return The count of produtos.
     */
    int getProdutosCount();
    /**
     * <pre>
     * List of products (repeated field)
     * </pre>
     *
     * <code>repeated string produtos = 2;</code>
     * @param index The index of the element to return.
     * @return The produtos at the given index.
     */
    java.lang.String getProdutos(int index);
    /**
     * <pre>
     * List of products (repeated field)
     * </pre>
     *
     * <code>repeated string produtos = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the produtos at the given index.
     */
    com.google.protobuf.ByteString
        getProdutosBytes(int index);

    /**
     * <pre>
     * Total value of the purchase
     * </pre>
     *
     * <code>int64 valorTotal = 3;</code>
     * @return The valorTotal.
     */
    long getValorTotal();
  }
  /**
   * <pre>
   * Message representing a Compra (purchase)
   * </pre>
   *
   * Protobuf type {@code compra.Compra}
   */
  public static final class Compra extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:compra.Compra)
      CompraOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Compra.class.getName());
    }
    // Use Compra.newBuilder() to construct.
    private Compra(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Compra() {
      nomeCliente_ = "";
      produtos_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return compra.CompraOuterClass.internal_static_compra_Compra_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return compra.CompraOuterClass.internal_static_compra_Compra_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              compra.CompraOuterClass.Compra.class, compra.CompraOuterClass.Compra.Builder.class);
    }

    public static final int NOMECLIENTE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nomeCliente_ = "";
    /**
     * <pre>
     * Name of the client
     * </pre>
     *
     * <code>string nomeCliente = 1;</code>
     * @return The nomeCliente.
     */
    @java.lang.Override
    public java.lang.String getNomeCliente() {
      java.lang.Object ref = nomeCliente_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeCliente_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Name of the client
     * </pre>
     *
     * <code>string nomeCliente = 1;</code>
     * @return The bytes for nomeCliente.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeClienteBytes() {
      java.lang.Object ref = nomeCliente_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeCliente_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUTOS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList produtos_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * List of products (repeated field)
     * </pre>
     *
     * <code>repeated string produtos = 2;</code>
     * @return A list containing the produtos.
     */
    public com.google.protobuf.ProtocolStringList
        getProdutosList() {
      return produtos_;
    }
    /**
     * <pre>
     * List of products (repeated field)
     * </pre>
     *
     * <code>repeated string produtos = 2;</code>
     * @return The count of produtos.
     */
    public int getProdutosCount() {
      return produtos_.size();
    }
    /**
     * <pre>
     * List of products (repeated field)
     * </pre>
     *
     * <code>repeated string produtos = 2;</code>
     * @param index The index of the element to return.
     * @return The produtos at the given index.
     */
    public java.lang.String getProdutos(int index) {
      return produtos_.get(index);
    }
    /**
     * <pre>
     * List of products (repeated field)
     * </pre>
     *
     * <code>repeated string produtos = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the produtos at the given index.
     */
    public com.google.protobuf.ByteString
        getProdutosBytes(int index) {
      return produtos_.getByteString(index);
    }

    public static final int VALORTOTAL_FIELD_NUMBER = 3;
    private long valorTotal_ = 0L;
    /**
     * <pre>
     * Total value of the purchase
     * </pre>
     *
     * <code>int64 valorTotal = 3;</code>
     * @return The valorTotal.
     */
    @java.lang.Override
    public long getValorTotal() {
      return valorTotal_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeCliente_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nomeCliente_);
      }
      for (int i = 0; i < produtos_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, produtos_.getRaw(i));
      }
      if (valorTotal_ != 0L) {
        output.writeInt64(3, valorTotal_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeCliente_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nomeCliente_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < produtos_.size(); i++) {
          dataSize += computeStringSizeNoTag(produtos_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProdutosList().size();
      }
      if (valorTotal_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, valorTotal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof compra.CompraOuterClass.Compra)) {
        return super.equals(obj);
      }
      compra.CompraOuterClass.Compra other = (compra.CompraOuterClass.Compra) obj;

      if (!getNomeCliente()
          .equals(other.getNomeCliente())) return false;
      if (!getProdutosList()
          .equals(other.getProdutosList())) return false;
      if (getValorTotal()
          != other.getValorTotal()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMECLIENTE_FIELD_NUMBER;
      hash = (53 * hash) + getNomeCliente().hashCode();
      if (getProdutosCount() > 0) {
        hash = (37 * hash) + PRODUTOS_FIELD_NUMBER;
        hash = (53 * hash) + getProdutosList().hashCode();
      }
      hash = (37 * hash) + VALORTOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValorTotal());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static compra.CompraOuterClass.Compra parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static compra.CompraOuterClass.Compra parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static compra.CompraOuterClass.Compra parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static compra.CompraOuterClass.Compra parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static compra.CompraOuterClass.Compra parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static compra.CompraOuterClass.Compra parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static compra.CompraOuterClass.Compra parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static compra.CompraOuterClass.Compra parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static compra.CompraOuterClass.Compra parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static compra.CompraOuterClass.Compra parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static compra.CompraOuterClass.Compra parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static compra.CompraOuterClass.Compra parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(compra.CompraOuterClass.Compra prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message representing a Compra (purchase)
     * </pre>
     *
     * Protobuf type {@code compra.Compra}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:compra.Compra)
        compra.CompraOuterClass.CompraOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return compra.CompraOuterClass.internal_static_compra_Compra_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return compra.CompraOuterClass.internal_static_compra_Compra_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                compra.CompraOuterClass.Compra.class, compra.CompraOuterClass.Compra.Builder.class);
      }

      // Construct using compra.CompraOuterClass.Compra.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nomeCliente_ = "";
        produtos_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        valorTotal_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return compra.CompraOuterClass.internal_static_compra_Compra_descriptor;
      }

      @java.lang.Override
      public compra.CompraOuterClass.Compra getDefaultInstanceForType() {
        return compra.CompraOuterClass.Compra.getDefaultInstance();
      }

      @java.lang.Override
      public compra.CompraOuterClass.Compra build() {
        compra.CompraOuterClass.Compra result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public compra.CompraOuterClass.Compra buildPartial() {
        compra.CompraOuterClass.Compra result = new compra.CompraOuterClass.Compra(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(compra.CompraOuterClass.Compra result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nomeCliente_ = nomeCliente_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          produtos_.makeImmutable();
          result.produtos_ = produtos_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.valorTotal_ = valorTotal_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof compra.CompraOuterClass.Compra) {
          return mergeFrom((compra.CompraOuterClass.Compra)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(compra.CompraOuterClass.Compra other) {
        if (other == compra.CompraOuterClass.Compra.getDefaultInstance()) return this;
        if (!other.getNomeCliente().isEmpty()) {
          nomeCliente_ = other.nomeCliente_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.produtos_.isEmpty()) {
          if (produtos_.isEmpty()) {
            produtos_ = other.produtos_;
            bitField0_ |= 0x00000002;
          } else {
            ensureProdutosIsMutable();
            produtos_.addAll(other.produtos_);
          }
          onChanged();
        }
        if (other.getValorTotal() != 0L) {
          setValorTotal(other.getValorTotal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nomeCliente_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureProdutosIsMutable();
                produtos_.add(s);
                break;
              } // case 18
              case 24: {
                valorTotal_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nomeCliente_ = "";
      /**
       * <pre>
       * Name of the client
       * </pre>
       *
       * <code>string nomeCliente = 1;</code>
       * @return The nomeCliente.
       */
      public java.lang.String getNomeCliente() {
        java.lang.Object ref = nomeCliente_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nomeCliente_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Name of the client
       * </pre>
       *
       * <code>string nomeCliente = 1;</code>
       * @return The bytes for nomeCliente.
       */
      public com.google.protobuf.ByteString
          getNomeClienteBytes() {
        java.lang.Object ref = nomeCliente_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nomeCliente_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Name of the client
       * </pre>
       *
       * <code>string nomeCliente = 1;</code>
       * @param value The nomeCliente to set.
       * @return This builder for chaining.
       */
      public Builder setNomeCliente(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nomeCliente_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name of the client
       * </pre>
       *
       * <code>string nomeCliente = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNomeCliente() {
        nomeCliente_ = getDefaultInstance().getNomeCliente();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name of the client
       * </pre>
       *
       * <code>string nomeCliente = 1;</code>
       * @param value The bytes for nomeCliente to set.
       * @return This builder for chaining.
       */
      public Builder setNomeClienteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nomeCliente_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList produtos_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureProdutosIsMutable() {
        if (!produtos_.isModifiable()) {
          produtos_ = new com.google.protobuf.LazyStringArrayList(produtos_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @return A list containing the produtos.
       */
      public com.google.protobuf.ProtocolStringList
          getProdutosList() {
        produtos_.makeImmutable();
        return produtos_;
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @return The count of produtos.
       */
      public int getProdutosCount() {
        return produtos_.size();
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @param index The index of the element to return.
       * @return The produtos at the given index.
       */
      public java.lang.String getProdutos(int index) {
        return produtos_.get(index);
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the produtos at the given index.
       */
      public com.google.protobuf.ByteString
          getProdutosBytes(int index) {
        return produtos_.getByteString(index);
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @param index The index to set the value at.
       * @param value The produtos to set.
       * @return This builder for chaining.
       */
      public Builder setProdutos(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProdutosIsMutable();
        produtos_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @param value The produtos to add.
       * @return This builder for chaining.
       */
      public Builder addProdutos(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProdutosIsMutable();
        produtos_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @param values The produtos to add.
       * @return This builder for chaining.
       */
      public Builder addAllProdutos(
          java.lang.Iterable<java.lang.String> values) {
        ensureProdutosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, produtos_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProdutos() {
        produtos_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of products (repeated field)
       * </pre>
       *
       * <code>repeated string produtos = 2;</code>
       * @param value The bytes of the produtos to add.
       * @return This builder for chaining.
       */
      public Builder addProdutosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureProdutosIsMutable();
        produtos_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long valorTotal_ ;
      /**
       * <pre>
       * Total value of the purchase
       * </pre>
       *
       * <code>int64 valorTotal = 3;</code>
       * @return The valorTotal.
       */
      @java.lang.Override
      public long getValorTotal() {
        return valorTotal_;
      }
      /**
       * <pre>
       * Total value of the purchase
       * </pre>
       *
       * <code>int64 valorTotal = 3;</code>
       * @param value The valorTotal to set.
       * @return This builder for chaining.
       */
      public Builder setValorTotal(long value) {

        valorTotal_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total value of the purchase
       * </pre>
       *
       * <code>int64 valorTotal = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValorTotal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        valorTotal_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:compra.Compra)
    }

    // @@protoc_insertion_point(class_scope:compra.Compra)
    private static final compra.CompraOuterClass.Compra DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new compra.CompraOuterClass.Compra();
    }

    public static compra.CompraOuterClass.Compra getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Compra>
        PARSER = new com.google.protobuf.AbstractParser<Compra>() {
      @java.lang.Override
      public Compra parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Compra> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Compra> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public compra.CompraOuterClass.Compra getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_compra_Compra_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_compra_Compra_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Compra.proto\022\006compra\"C\n\006Compra\022\023\n\013nome" +
      "Cliente\030\001 \001(\t\022\020\n\010produtos\030\002 \003(\t\022\022\n\nvalor" +
      "Total\030\003 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_compra_Compra_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_compra_Compra_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_compra_Compra_descriptor,
        new java.lang.String[] { "NomeCliente", "Produtos", "ValorTotal", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
