// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: compra.proto
// Protobuf Java Version: 4.29.0

public final class CompraOuterClass {
  private CompraOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      CompraOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompraOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Compra)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nomeCliente = 1;</code>
     * @return The nomeCliente.
     */
    java.lang.String getNomeCliente();
    /**
     * <code>string nomeCliente = 1;</code>
     * @return The bytes for nomeCliente.
     */
    com.google.protobuf.ByteString
        getNomeClienteBytes();

    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    java.util.List<CompraOuterClass.Produto> 
        getProdutosList();
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    CompraOuterClass.Produto getProdutos(int index);
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    int getProdutosCount();
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    java.util.List<? extends CompraOuterClass.ProdutoOrBuilder> 
        getProdutosOrBuilderList();
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    CompraOuterClass.ProdutoOrBuilder getProdutosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Compra}
   */
  public static final class Compra extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Compra)
      CompraOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Compra.class.getName());
    }
    // Use Compra.newBuilder() to construct.
    private Compra(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Compra() {
      nomeCliente_ = "";
      produtos_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CompraOuterClass.internal_static_Compra_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CompraOuterClass.internal_static_Compra_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CompraOuterClass.Compra.class, CompraOuterClass.Compra.Builder.class);
    }

    public static final int NOMECLIENTE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nomeCliente_ = "";
    /**
     * <code>string nomeCliente = 1;</code>
     * @return The nomeCliente.
     */
    @java.lang.Override
    public java.lang.String getNomeCliente() {
      java.lang.Object ref = nomeCliente_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeCliente_ = s;
        return s;
      }
    }
    /**
     * <code>string nomeCliente = 1;</code>
     * @return The bytes for nomeCliente.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeClienteBytes() {
      java.lang.Object ref = nomeCliente_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeCliente_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUTOS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<CompraOuterClass.Produto> produtos_;
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    @java.lang.Override
    public java.util.List<CompraOuterClass.Produto> getProdutosList() {
      return produtos_;
    }
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends CompraOuterClass.ProdutoOrBuilder> 
        getProdutosOrBuilderList() {
      return produtos_;
    }
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    @java.lang.Override
    public int getProdutosCount() {
      return produtos_.size();
    }
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    @java.lang.Override
    public CompraOuterClass.Produto getProdutos(int index) {
      return produtos_.get(index);
    }
    /**
     * <code>repeated .Produto produtos = 2;</code>
     */
    @java.lang.Override
    public CompraOuterClass.ProdutoOrBuilder getProdutosOrBuilder(
        int index) {
      return produtos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeCliente_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nomeCliente_);
      }
      for (int i = 0; i < produtos_.size(); i++) {
        output.writeMessage(2, produtos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeCliente_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nomeCliente_);
      }
      for (int i = 0; i < produtos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, produtos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CompraOuterClass.Compra)) {
        return super.equals(obj);
      }
      CompraOuterClass.Compra other = (CompraOuterClass.Compra) obj;

      if (!getNomeCliente()
          .equals(other.getNomeCliente())) return false;
      if (!getProdutosList()
          .equals(other.getProdutosList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMECLIENTE_FIELD_NUMBER;
      hash = (53 * hash) + getNomeCliente().hashCode();
      if (getProdutosCount() > 0) {
        hash = (37 * hash) + PRODUTOS_FIELD_NUMBER;
        hash = (53 * hash) + getProdutosList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CompraOuterClass.Compra parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CompraOuterClass.Compra parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CompraOuterClass.Compra parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CompraOuterClass.Compra parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CompraOuterClass.Compra parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CompraOuterClass.Compra parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CompraOuterClass.Compra parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CompraOuterClass.Compra parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CompraOuterClass.Compra parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CompraOuterClass.Compra parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CompraOuterClass.Compra parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CompraOuterClass.Compra parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CompraOuterClass.Compra prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Compra}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Compra)
        CompraOuterClass.CompraOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CompraOuterClass.internal_static_Compra_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CompraOuterClass.internal_static_Compra_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CompraOuterClass.Compra.class, CompraOuterClass.Compra.Builder.class);
      }

      // Construct using CompraOuterClass.Compra.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nomeCliente_ = "";
        if (produtosBuilder_ == null) {
          produtos_ = java.util.Collections.emptyList();
        } else {
          produtos_ = null;
          produtosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CompraOuterClass.internal_static_Compra_descriptor;
      }

      @java.lang.Override
      public CompraOuterClass.Compra getDefaultInstanceForType() {
        return CompraOuterClass.Compra.getDefaultInstance();
      }

      @java.lang.Override
      public CompraOuterClass.Compra build() {
        CompraOuterClass.Compra result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CompraOuterClass.Compra buildPartial() {
        CompraOuterClass.Compra result = new CompraOuterClass.Compra(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(CompraOuterClass.Compra result) {
        if (produtosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            produtos_ = java.util.Collections.unmodifiableList(produtos_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.produtos_ = produtos_;
        } else {
          result.produtos_ = produtosBuilder_.build();
        }
      }

      private void buildPartial0(CompraOuterClass.Compra result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nomeCliente_ = nomeCliente_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CompraOuterClass.Compra) {
          return mergeFrom((CompraOuterClass.Compra)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CompraOuterClass.Compra other) {
        if (other == CompraOuterClass.Compra.getDefaultInstance()) return this;
        if (!other.getNomeCliente().isEmpty()) {
          nomeCliente_ = other.nomeCliente_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (produtosBuilder_ == null) {
          if (!other.produtos_.isEmpty()) {
            if (produtos_.isEmpty()) {
              produtos_ = other.produtos_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureProdutosIsMutable();
              produtos_.addAll(other.produtos_);
            }
            onChanged();
          }
        } else {
          if (!other.produtos_.isEmpty()) {
            if (produtosBuilder_.isEmpty()) {
              produtosBuilder_.dispose();
              produtosBuilder_ = null;
              produtos_ = other.produtos_;
              bitField0_ = (bitField0_ & ~0x00000002);
              produtosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProdutosFieldBuilder() : null;
            } else {
              produtosBuilder_.addAllMessages(other.produtos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nomeCliente_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                CompraOuterClass.Produto m =
                    input.readMessage(
                        CompraOuterClass.Produto.parser(),
                        extensionRegistry);
                if (produtosBuilder_ == null) {
                  ensureProdutosIsMutable();
                  produtos_.add(m);
                } else {
                  produtosBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nomeCliente_ = "";
      /**
       * <code>string nomeCliente = 1;</code>
       * @return The nomeCliente.
       */
      public java.lang.String getNomeCliente() {
        java.lang.Object ref = nomeCliente_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nomeCliente_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nomeCliente = 1;</code>
       * @return The bytes for nomeCliente.
       */
      public com.google.protobuf.ByteString
          getNomeClienteBytes() {
        java.lang.Object ref = nomeCliente_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nomeCliente_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nomeCliente = 1;</code>
       * @param value The nomeCliente to set.
       * @return This builder for chaining.
       */
      public Builder setNomeCliente(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nomeCliente_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nomeCliente = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNomeCliente() {
        nomeCliente_ = getDefaultInstance().getNomeCliente();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nomeCliente = 1;</code>
       * @param value The bytes for nomeCliente to set.
       * @return This builder for chaining.
       */
      public Builder setNomeClienteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nomeCliente_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<CompraOuterClass.Produto> produtos_ =
        java.util.Collections.emptyList();
      private void ensureProdutosIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          produtos_ = new java.util.ArrayList<CompraOuterClass.Produto>(produtos_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          CompraOuterClass.Produto, CompraOuterClass.Produto.Builder, CompraOuterClass.ProdutoOrBuilder> produtosBuilder_;

      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public java.util.List<CompraOuterClass.Produto> getProdutosList() {
        if (produtosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(produtos_);
        } else {
          return produtosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public int getProdutosCount() {
        if (produtosBuilder_ == null) {
          return produtos_.size();
        } else {
          return produtosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public CompraOuterClass.Produto getProdutos(int index) {
        if (produtosBuilder_ == null) {
          return produtos_.get(index);
        } else {
          return produtosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder setProdutos(
          int index, CompraOuterClass.Produto value) {
        if (produtosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProdutosIsMutable();
          produtos_.set(index, value);
          onChanged();
        } else {
          produtosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder setProdutos(
          int index, CompraOuterClass.Produto.Builder builderForValue) {
        if (produtosBuilder_ == null) {
          ensureProdutosIsMutable();
          produtos_.set(index, builderForValue.build());
          onChanged();
        } else {
          produtosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder addProdutos(CompraOuterClass.Produto value) {
        if (produtosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProdutosIsMutable();
          produtos_.add(value);
          onChanged();
        } else {
          produtosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder addProdutos(
          int index, CompraOuterClass.Produto value) {
        if (produtosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProdutosIsMutable();
          produtos_.add(index, value);
          onChanged();
        } else {
          produtosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder addProdutos(
          CompraOuterClass.Produto.Builder builderForValue) {
        if (produtosBuilder_ == null) {
          ensureProdutosIsMutable();
          produtos_.add(builderForValue.build());
          onChanged();
        } else {
          produtosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder addProdutos(
          int index, CompraOuterClass.Produto.Builder builderForValue) {
        if (produtosBuilder_ == null) {
          ensureProdutosIsMutable();
          produtos_.add(index, builderForValue.build());
          onChanged();
        } else {
          produtosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder addAllProdutos(
          java.lang.Iterable<? extends CompraOuterClass.Produto> values) {
        if (produtosBuilder_ == null) {
          ensureProdutosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, produtos_);
          onChanged();
        } else {
          produtosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder clearProdutos() {
        if (produtosBuilder_ == null) {
          produtos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          produtosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public Builder removeProdutos(int index) {
        if (produtosBuilder_ == null) {
          ensureProdutosIsMutable();
          produtos_.remove(index);
          onChanged();
        } else {
          produtosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public CompraOuterClass.Produto.Builder getProdutosBuilder(
          int index) {
        return getProdutosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public CompraOuterClass.ProdutoOrBuilder getProdutosOrBuilder(
          int index) {
        if (produtosBuilder_ == null) {
          return produtos_.get(index);  } else {
          return produtosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public java.util.List<? extends CompraOuterClass.ProdutoOrBuilder> 
           getProdutosOrBuilderList() {
        if (produtosBuilder_ != null) {
          return produtosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(produtos_);
        }
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public CompraOuterClass.Produto.Builder addProdutosBuilder() {
        return getProdutosFieldBuilder().addBuilder(
            CompraOuterClass.Produto.getDefaultInstance());
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public CompraOuterClass.Produto.Builder addProdutosBuilder(
          int index) {
        return getProdutosFieldBuilder().addBuilder(
            index, CompraOuterClass.Produto.getDefaultInstance());
      }
      /**
       * <code>repeated .Produto produtos = 2;</code>
       */
      public java.util.List<CompraOuterClass.Produto.Builder> 
           getProdutosBuilderList() {
        return getProdutosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CompraOuterClass.Produto, CompraOuterClass.Produto.Builder, CompraOuterClass.ProdutoOrBuilder> 
          getProdutosFieldBuilder() {
        if (produtosBuilder_ == null) {
          produtosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CompraOuterClass.Produto, CompraOuterClass.Produto.Builder, CompraOuterClass.ProdutoOrBuilder>(
                  produtos_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          produtos_ = null;
        }
        return produtosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Compra)
    }

    // @@protoc_insertion_point(class_scope:Compra)
    private static final CompraOuterClass.Compra DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CompraOuterClass.Compra();
    }

    public static CompraOuterClass.Compra getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Compra>
        PARSER = new com.google.protobuf.AbstractParser<Compra>() {
      @java.lang.Override
      public Compra parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Compra> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Compra> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CompraOuterClass.Compra getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProdutoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Produto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>float valor = 2;</code>
     * @return The valor.
     */
    float getValor();
  }
  /**
   * Protobuf type {@code Produto}
   */
  public static final class Produto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Produto)
      ProdutoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Produto.class.getName());
    }
    // Use Produto.newBuilder() to construct.
    private Produto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Produto() {
      nome_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CompraOuterClass.internal_static_Produto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CompraOuterClass.internal_static_Produto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CompraOuterClass.Produto.class, CompraOuterClass.Produto.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nome_ = "";
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALOR_FIELD_NUMBER = 2;
    private float valor_ = 0F;
    /**
     * <code>float valor = 2;</code>
     * @return The valor.
     */
    @java.lang.Override
    public float getValor() {
      return valor_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nome_);
      }
      if (java.lang.Float.floatToRawIntBits(valor_) != 0) {
        output.writeFloat(2, valor_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nome_);
      }
      if (java.lang.Float.floatToRawIntBits(valor_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, valor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CompraOuterClass.Produto)) {
        return super.equals(obj);
      }
      CompraOuterClass.Produto other = (CompraOuterClass.Produto) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (java.lang.Float.floatToIntBits(getValor())
          != java.lang.Float.floatToIntBits(
              other.getValor())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + VALOR_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getValor());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CompraOuterClass.Produto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CompraOuterClass.Produto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CompraOuterClass.Produto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CompraOuterClass.Produto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CompraOuterClass.Produto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CompraOuterClass.Produto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CompraOuterClass.Produto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CompraOuterClass.Produto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CompraOuterClass.Produto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CompraOuterClass.Produto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CompraOuterClass.Produto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CompraOuterClass.Produto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CompraOuterClass.Produto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Produto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Produto)
        CompraOuterClass.ProdutoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CompraOuterClass.internal_static_Produto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CompraOuterClass.internal_static_Produto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CompraOuterClass.Produto.class, CompraOuterClass.Produto.Builder.class);
      }

      // Construct using CompraOuterClass.Produto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nome_ = "";
        valor_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CompraOuterClass.internal_static_Produto_descriptor;
      }

      @java.lang.Override
      public CompraOuterClass.Produto getDefaultInstanceForType() {
        return CompraOuterClass.Produto.getDefaultInstance();
      }

      @java.lang.Override
      public CompraOuterClass.Produto build() {
        CompraOuterClass.Produto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CompraOuterClass.Produto buildPartial() {
        CompraOuterClass.Produto result = new CompraOuterClass.Produto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CompraOuterClass.Produto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nome_ = nome_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.valor_ = valor_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CompraOuterClass.Produto) {
          return mergeFrom((CompraOuterClass.Produto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CompraOuterClass.Produto other) {
        if (other == CompraOuterClass.Produto.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getValor() != 0F) {
          setValor(other.getValor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nome_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 21: {
                valor_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nome_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        nome_ = getDefaultInstance().getNome();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nome_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private float valor_ ;
      /**
       * <code>float valor = 2;</code>
       * @return The valor.
       */
      @java.lang.Override
      public float getValor() {
        return valor_;
      }
      /**
       * <code>float valor = 2;</code>
       * @param value The valor to set.
       * @return This builder for chaining.
       */
      public Builder setValor(float value) {

        valor_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float valor = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        valor_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Produto)
    }

    // @@protoc_insertion_point(class_scope:Produto)
    private static final CompraOuterClass.Produto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CompraOuterClass.Produto();
    }

    public static CompraOuterClass.Produto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Produto>
        PARSER = new com.google.protobuf.AbstractParser<Produto>() {
      @java.lang.Override
      public Produto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Produto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Produto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CompraOuterClass.Produto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Compra_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Compra_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Produto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Produto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014compra.proto\"9\n\006Compra\022\023\n\013nomeCliente\030" +
      "\001 \001(\t\022\032\n\010produtos\030\002 \003(\0132\010.Produto\"&\n\007Pro" +
      "duto\022\014\n\004nome\030\001 \001(\t\022\r\n\005valor\030\002 \001(\002b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Compra_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Compra_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Compra_descriptor,
        new java.lang.String[] { "NomeCliente", "Produtos", });
    internal_static_Produto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Produto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Produto_descriptor,
        new java.lang.String[] { "Nome", "Valor", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
